# This workflow will build a package using Maven, publish it to GitHub packages, and create a release when a tag is pushed
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Release and Publish

on:
  push:
    tags:
      - "v*"
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: バージョン情報の確認
        run: mvn versions:display-property-updates

      - name: テストとビルド
        run: mvn -B verify --file pom.xml

      - name: カバレッジレポートのアップロード
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/
          retention-days: 7

      - name: Publish to GitHub Packages
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/kmg-core-*.jar
          generate_release_notes: true
          body: |
            ## 成果物
            - JARファイル: `target/kmg-core-*.jar`
            
            ## テスト結果
            - JUnitテストレポート: `target/surefire-reports/`
            - カバレッジレポート: `target/site/jacoco/`
