name: Release

on:
  push:
    tags:
      - "v*"

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: バージョン情報の確認
        run: mvn versions:display-property-updates

      - name: テストとビルド
        run: mvn -B verify --file pom.xml

      - name: カバレッジレポートのアップロード
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/
          retention-days: 7

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/kmg-core-*.jar
          generate_release_notes: true
          body: |
            ## 成果物
            - JARファイル: `target/kmg-core-*.jar`
            
            ## テスト結果
            - JUnitテストレポート: `target/surefire-reports/`
            - カバレッジレポート: `target/site/jacoco/`
